version: '3'

services:
  db:
    build: requirement/mariadb
    volumes:
    -  /home/fmonbeig/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress

  # wordpress:
  #   depends_on:
  #     - db
  #   build: requirement/wordpress
  #   ports:
  #     - "8000:80"
  #   restart: always
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #     WORDPRESS_DB_NAME: wordpress


# On peut mettre des variables d'env
# ex : image: "webapp:${TAG}"
#
#
