version: '3'

services:
  db:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    image: mariadb
    volumes:
    - /home/user42/data:/var/lib/mysql
    restart: always

  # wordpress:
  #   depends_on:
  #     - db
  #   build: requirement/wordpress
  #   container_name: mariadb
  #   ports:
  #     - "8000:80"
  #   restart: always
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #     WORDPRESS_DB_NAME: wordpress


# On peut mettre des variables d'env
# ex : image: "webapp:${TAG}"
#
#
