version: '3'

services:
#------------MARIADB------------#
  db:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    image: mariadb
    volumes:
    - /home/user42/data:/var/lib/mysql
    restart: always

#------------WORDPRESS------------#

  wordpress:
    depends_on:
      - db
    build: requirement/wordpress
    container_name: wordpress
    env_file: .env
    image : wordpress
    volumes:
    - www:/var/www/html
    restart: always

#------------VOLUMES------------#
volumes:
    database:
       driver: local # default
       driver_opts:
         type: none
         device: ${VOLUME_DATABASE}
         o: bind
    www:
       driver: local # default
       driver_opts:
         type: none
         device: ${VOLUME_WEBSITE}
         o: bind

#------------NETWORKS------------#

# networks:
#   inception:
#     name: ???
#     driver: ???

# On peut mettre des variables d'env
# ex : image: "webapp:${TAG}"
#
#
