version: '3.1'

services:
#------------MARIADB------------#
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    env_file: ./.env
    image: mariadb
    volumes:
    - maria_database:/var/lib/mysql
    networks:
      - inception
    restart: always

#------------WORDPRESS------------#
  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    container_name: wordpress
    env_file: ./.env
    image : wordpress
    volumes:
    - web_site:/var/www/html
    networks:
      - inception
    restart: always

#------------NGINX------------#
  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    container_name: nginx
    env_file: ./.env
    image : nginx
    ports:
      - "443:443"
    volumes:
    - web_site:/var/www/html  #it's the same that wordpress because html file have to be in this two place
    networks:
      - inception
    restart: always

#------------NETWORKS------------#
networks:
  inception:
    driver: bridge

#------------VOLUMES------------#
volumes:
    maria_database:
       driver: local # default
       driver_opts:
         type: none
         device: /home/fmonbeig/data/database
         o: bind
    web_site:
       driver: local
       driver_opts:
         type: none
         device: /home/fmonbeig/data/www
         o: bind


#with bridge we can create an intern network for all the containers (great when you have one service per container)
