version: '3'

services:
#------------MARIADB------------#
  db:
    build: requirements/mariadb
    container_name: mariadb
    env_file: .env
    image: mariadb
    volumes:
    - database:/var/lib/mysql
    restart: always

#------------WORDPRESS------------#
  # wordpress:
  #   depends_on:
  #     - db
  #   build: requirements/wordpress
  #   container_name: wordpress
  #   env_file: .env
  #   image : wordpress
  #   volumes:
  #   - www:/var/www/html
  #   restart: always

#------------VOLUMES------------#
volumes:
    database:
       driver: local # default
       driver_opts:
         type: none
         device: ${VOLUME_DATABASE}
         o: bind
    # www:
    #    driver: local # default
    #    driver_opts:
    #      type: none
    #      device: ${VOLUME_WEBSITE}
    #      o: bind

#------------NETWORKS------------#

# networks:
#   inception:
#     name: ???
#     driver: ???

#mkdir -p PATH construit le chemin et les dossier en recursif (a mettre dans le makefile ??)
