FROM alpine:3.14  ou FROM debian:9 (Download the OS with FROM)


RUN is for executing a command in the container (we have to limit the use of RUN to reduce the numbers of layers)
RUN apt-get update -yq \
&& apt-get install curl gnupg -yq \
&& curl -sL https://deb.nodesource.com/setup_10.x | bash \
&& apt-get install nodejs -yq \
&& apt-get clean -y

ADD permet de copier des elements dans un dossier
Ici c'est les elements de notre rep courant qui sera dans le dossier /app de l'image
elements qui ont été téléchargé via le apt-get
ADD . /app/

WORKDIR permet de se deplacer dans un dossier (change le repertoire courant)
WORKDIR /app

EXPOSE permet de preciser sur quel port l'application ecoute
Expose 2020

VOLUME permet d'indiquer quel répertoire vous voulez partager avec votre host.

CMD est la commande que fait le conteneur lors de son demarrage
CMD ["echo", "Hello World !"]  (Do the command)


FROM	permet de définir l'image source ;
RUN		permet d’exécuter des commandes dans votre conteneur ;
ADD		permet d'ajouter des fichiers dans votre conteneur ;
WORKDIR	permet de définir votre répertoire de travail ;
EXPOSE	permet de définir les ports d'écoute par défaut ;
VOLUME	permet de définir les volumes utilisables ;
CMD		permet de définir la commande par défaut lors de l’exécution de vos conteneurs Docker.
ENTRYPOINT	(pareil qu'au dessus mais ne peut pas etre bloquer par un docker-compose ou une ligne de command)
COPY	Permet de copier un element de son PC sur son containers

.dockerignore permet de ne pas bouger certains fichiers avec ADD

